version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.2.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            yarn
            yarn build

workflows:
  export-workflow:
    jobs:
      - build
